#!/usr/bin/env python3
"""Generate main/font.h: 1bpp bitmap font (ASCII 32..126) from a system TTF.

Usage: tools/gen_font.py [ttf] [cell_w] [cell_h] [pt_size]
Each glyph is cell_h rows; each row is ceil(cell_w/8) bytes, MSB = leftmost pixel.
"""
import sys, math
from PIL import Image, ImageDraw, ImageFont

ttf = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/dejavu-sans-mono-fonts/DejaVuSansMono-Bold.ttf"
W = int(sys.argv[2]) if len(sys.argv) > 2 else 12
H = int(sys.argv[3]) if len(sys.argv) > 3 else 20
PT = int(sys.argv[4]) if len(sys.argv) > 4 else 18
OUT = sys.argv[5] if len(sys.argv) > 5 else "main/font.h"

font = ImageFont.truetype(ttf, PT)
bpr = math.ceil(W / 8)
ascent, descent = font.getmetrics()
yoff = (H - (ascent + descent)) // 2

glyphs = []
for code in range(32, 127):
    img = Image.new("1", (W, H), 0)
    d = ImageDraw.Draw(img)
    ch = chr(code)
    bbox = font.getbbox(ch)
    gw = bbox[2] - bbox[0]
    x = (W - gw) // 2 - bbox[0]
    d.text((x, yoff), ch, font=font, fill=1)
    rows = []
    for y in range(H):
        row = 0
        for xx in range(W):
            if img.getpixel((xx, y)):
                row |= 1 << (bpr * 8 - 1 - xx)
        rows.append(row)
    glyphs.append(rows)

with open(OUT, "w") as f:
    f.write("/* Auto-generated by tools/gen_font.py from %s (%dpt). Do not edit. */\n" % (ttf.split('/')[-1], PT))
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("#define FONT_W %d\n#define FONT_H %d\n#define FONT_BPR %d\n#define FONT_FIRST 32\n#define FONT_LAST 126\n\n" % (W, H, bpr))
    f.write("static const uint8_t font_glyphs[%d][FONT_H * FONT_BPR] = {\n" % len(glyphs))
    for code, rows in zip(range(32, 127), glyphs):
        f.write("    /* %3d '%s' */ {" % (code, chr(code) if chr(code) not in "\\'" else "\\" + chr(code)))
        bs = []
        for row in rows:
            for b in range(bpr):
                bs.append("0x%02x" % ((row >> (8 * (bpr - 1 - b))) & 0xff))
        f.write(", ".join(bs))
        f.write("},\n")
    f.write("};\n")
print("wrote", OUT, "%dx%d, %d glyphs" % (W, H, len(glyphs)))
